// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FetchFlow.Database.Service.Context;

#nullable disable

namespace FetchFlow.Database.Service.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20250720121508_AllowNullableFields")]
    partial class AllowNullableFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Staj.WebApi.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KapMemberTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KapMemberType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MkkMemberOid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RelatedMemberOid")
                        .HasColumnType("longtext");

                    b.Property<string>("RelatedMemberTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("StockCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
